<?php

namespace App\Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;
    private $concesionarios;
    private $vehiculos;
    
    public function __construct() 
    {
        $this->concesionarios = new ArrayCollection();
        $this->vehiculos = new ArrayCollection();
    }          

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Get concesionarios
     */
    public function getConcesionarios()
    {
        return $this->concesionarios;
    }
    
    /**
     * Get concesionarios
     */
    public function getVehiculos()
    {
        return $this->vehiculos;
    }
        
    
}
